baseURL: /
languageCode: en-us
title: Learning blog
theme: mini
paginate: 10
relativeURLS: true


hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

markup:
  highlight:
    guessSyntax: true
    style: emacs

social:
  github: https://github.com/bitnose
  stackoverflow: https://stackoverflow.com/users/9491568/anniina


params:
  author: 
  bio: 
  description: "."
  enableRSS: false
  enableComments: true
  enableGoogleAnalytics: false
  hiddenPostSummaryInHomePage: true
