baseURL: /
languageCode: en-us
title: Learning blog
theme: mini
paginate: 3
relativeURLS: true


hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

markup:
  highlight:
    guessSyntax: true
    style: emacs

social:
  github: https://github.com/
  stackoverflow: https://stackoverflow.com/users/


params:
  author: Anniina Korkiakangas
  bio: 
  description: "."
  enableRSS: false
  enableComments: false
  enableGoogleAnalytics: false
